POST http://localhost:3333/posts
Content-Type: application/json

{
    "title": "test",
    "postType": "post",
    "slug": "test-post",
    "status": "draft",
    "content": "test content",
    "featuredImageUrl": "www.dkdev.de/image",
    "publishedOn": "2026-03-31T13:38:32+0000",
    "tags": ["nestjs", "typescript"],
    "metaOptions": [
        {
            "key": "testkey",
            "value": "testvalue"
        }
    ]
}