POST http://localhost:3333/users
Content-Type: application/json

{
    "firstName": "Domi",
    "lastName": "DKI",
    "email": "dk@dk.de",
    "password": "test123@"
}

POST http://localhost:3333/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoiZGtAZGsuZGUiLCJpYXQiOjE3NzUzNzQ0MzIsImV4cCI6MTc3NTM3ODAzMiwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.rP6OzwZYPtJw827z5ro8Q6FFnX2cxXDpwl4e1wsxrM8

{
    "users": [
        {
            "firstName": "Domi",
            "lastName": "DKI",
            "email": "dk@dk.com",
            "password": "test123!"
        }, 
        {
            "firstName": "Domi",
            "lastName": "DKI",
            "email": "dk@dk.test",
            "password": "test123@"
        }
    ]
}